# command line: main.py recognition -c config/mtgea/dguha/radar_alone_test.yaml --weights after1021/2.5s/radar32(250:300)_kdmodel/120_74.53416149068323_epoch220_model.pt --phase slidingtest

base_lr: 0.01
batch_size: 256
chunk: 1
config: config/mtgea/dguha/radar_alone_test.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
kd_model: 'null'
log_interval: 100
model: net.st_gcn_alone.alone
model_args:
    base_model: net.st_gcn.Model
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 32
    output_class: 7
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: slidingtest
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
skeleton_test_feeder_args:
    data_path: /home/eslabkh/kh/dguha_dataset/dguha_sk_test.npy
    label_path: /home/eslabkh/kh/dguha_dataset/dguha_test_label.pkl
skeleton_train_feeder_args: {}
start_epoch: 0
step: []
test_batch_size: 13
test_feeder_args:
    data_path: /home/eslabkh/kh/dguha_dataset/dguha_pcl_ahc_test.npy
    label_path: /home/eslabkh/kh/dguha_dataset/dguha_test_label.pkl
train_feeder_args:
    data_path: /home/eslabkh/kh/dguha_dataset/dguha_pcl_ahc_train.npy
    label_path: /home/eslabkh/kh/dguha_dataset/dguha_train_label.pkl
use_gpu: true
weight_decay: 0.0001
weights: after1021/2.5s/radar32(250:300)_kdmodel/120_74.53416149068323_epoch220_model.pt
work_dir: ./work_dir/tmp
