# command line: main.py recognition --phase onnx --weights after1023/5s/nonkdmodel/radar4(200:300)/ra4_5s_70.pt -c config/mtgea/dguha/onnx10s.yaml

base_lr: 0.1
batch_size: 1
chunk: 1
config: config/mtgea/dguha/onnx10s.yaml
debug: false
device:
- 1
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
kd_model: 'null'
log_interval: 100
model: net.st_gcn_alone.alone
model_args:
    base_model: net.st_gcn.Model
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 32
    output_class: 7
nesterov: true
num_epoch: 300
num_worker: 4
optimizer: SGD
pavi_log: false
phase: onnx
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
skeleton_test_feeder_args: {}
skeleton_train_feeder_args: {}
start_epoch: 0
step:
- 10
- 50
test_batch_size: 1
test_feeder_args:
    data_path: /home/eslabkh/kh/dguha_dataset/train_5s_0.npy
    label_path: /home/eslabkh/kh/dguha_dataset/label_5s.pkl
train_feeder_args:
    data_path: /home/eslabkh/kh/dguha_dataset/train_10s.npy
    label_path: /home/eslabkh/kh/dguha_dataset/label_10s.pkl
use_gpu: true
weight_decay: 0.0001
weights: after1023/5s/nonkdmodel/radar4(200:300)/ra4_5s_70.pt
work_dir: ./work_dir/recognition/ST-GCN/alone/channel60/
